# permissions for end users to view certmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cert-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: certmanager-viewer-role
rules:
- apiGroups:
  - infra.infra.vexxhost.cloud
  resources:
  - certmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.infra.vexxhost.cloud
  resources:
  - certmanagers/status
  verbs:
  - get
